version: "3.8"

services:
  omniroot:
    image: jahanzeb833/omniroot-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omniroot-agent
    ports:
      - "5001:5001"
      - "5173:5173"
      - "8080:8080"  # Added port mapping for code-server
    volumes:
      - omniroot-data:/app/workspace
      - omniroot-db:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  omniroot-data:
  omniroot-db: